catalog:
  prettier: ^3.8.1

enableTelemetry: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - current
    - darwin
    - linux
